#!/bin/bash

# 🥷 Ninja Runner - Publishing Script
echo "🥷 Preparing Ninja Runner for Publishing..."
echo ""

echo "========================================================================="
echo "🛒 OPTION 1: Publish to VS Code Marketplace"
echo "========================================================================="
echo "🔐 Step 1: Login to marketplace"
echo "   Run: vsce login akhilninja"
echo "   Enter your Personal Access Token when prompted"
echo ""
echo "🚀 Step 2: Publish extension"
echo "   Run: vsce publish"
echo ""
echo "📈 Alternative: Publish with version bump"
echo "   Run: vsce publish patch  # for 0.0.2"
echo "   Run: vsce publish minor  # for 0.1.0"
echo "   Run: vsce publish major  # for 1.0.0"
echo ""
echo "🔗 Available at: https://marketplace.visualstudio.com/items?itemName=akhilninja.ninja-runner"
echo ""

echo "========================================================================="
echo "🌌 OPTION 2: Publish to Open VSX Registry (Antigravity Marketplace)"
echo "========================================================================="
echo "ℹ️  Antigravity IDE uses the Open VSX Registry (open-vsx.org) by default."
echo ""
echo "🔐 Step 1: Sign up and get a token"
echo "   1. Create an account at https://open-vsx.org/"
echo "   2. Link your GitHub account and sign the Publisher Agreement on your profile"
echo "   3. Go to Settings > Access Tokens, generate a token, and export it:"
echo "      export OVSX_PAT=\"your-access-token\""
echo ""
echo "📛 Step 2: Create namespace (First time only)"
echo "   Create a namespace matching the publisher in package.json (akhilninja):"
echo "   npx ovsx create-namespace akhilninja -p \$OVSX_PAT"
echo ""
echo "🚀 Step 3: Publish extension"
echo "   Publish directly from the extension folder:"
echo "   npx ovsx publish -p \$OVSX_PAT"
echo ""
echo "💡 Node.js Note:"
echo "   If you encounter an undici ReferenceError on Node 18, run these commands first:"
echo "   source ~/.nvm/nvm.sh"
echo "   nvm use 20"
echo "   npx ovsx publish -p \$OVSX_PAT"
echo ""
echo "🔗 Available at: https://open-vsx.org/extension/akhilninja/ninja-runner"
echo "========================================================================="
echo ""
echo "📝 Don't forget to:"
echo "1. Create GitHub repository and push your code"
echo "2. Update repository URLs in package.json"
echo "3. Add screenshots to your README"
echo "4. Tag your release on GitHub"
